export const brandIdToName = (id) => {
    const brands = [
        "Nvidia",
        "AMD",
        "Intel",
        "Crucial",
        "Corsair",
        "HyperX",
        "G.SKILL",
        "WD",
        "Samsung",
        "Gigabyte",
        "Sabrent",
        "HP",
        "Seagate",
        "Toshiba",
        "INTEL",
        "ASUS",
        "Deepcool",
        "Gamemax",
        "RedDragon",
        "Aerocool",
        "Cooler Master",
        "MSI",
        "Game Pro",
        "Kolink",
        "Cougar",
        "LG",
        "Logitech",
        "HyperX",
        "Logitech ",
        "Genius",
        "Redragon",
        "FAN",
        "Be quiet",
        "ID-Cooling",
    ];

    return brands[id - 1];
};
